---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:11.1.0
  amd64: ghcr.io/hassio-addons/base/amd64:11.1.0
  armhf: ghcr.io/hassio-addons/base/armhf:11.1.0
  armv7: ghcr.io/hassio-addons/base/armv7:11.1.0
  i386: ghcr.io/hassio-addons/base/i386:11.1.0
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
