---
build_from:
  aarch64: ghcr.io/hassio-addons/base:13.1.4
  amd64: ghcr.io/hassio-addons/base:13.1.4
  armhf: ghcr.io/hassio-addons/base:13.1.4
  armv7: ghcr.io/hassio-addons/base:13.1.4
  i386: ghcr.io/hassio-addons/base:13.1.4
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
