---
build_from:
  aarch64: ghcr.io/hassio-addons/base:13.1.5
  amd64: ghcr.io/hassio-addons/base:13.1.5
  armhf: ghcr.io/hassio-addons/base:13.1.5
  armv7: ghcr.io/hassio-addons/base:13.1.5
  i386: ghcr.io/hassio-addons/base:13.1.5
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
