---
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.3.0
  amd64: ghcr.io/hassio-addons/base:14.3.0
  armv7: ghcr.io/hassio-addons/base:14.3.0
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
