---
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.0.8
  amd64: ghcr.io/hassio-addons/base:14.0.8
  armhf: ghcr.io/hassio-addons/base:14.0.8
  armv7: ghcr.io/hassio-addons/base:14.0.8
  i386: ghcr.io/hassio-addons/base:14.0.8
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
