---
build_from:
  aarch64: ghcr.io/hassio-addons/base-nodejs:0.2.3
  amd64: ghcr.io/hassio-addons/base-nodejs:0.2.3
  armv7: ghcr.io/hassio-addons/base-nodejs:0.2.3
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
