---
build_from:
  aarch64: ghcr.io/hassio-addons/base:12.2.7
  amd64: ghcr.io/hassio-addons/base:12.2.7
  armhf: ghcr.io/hassio-addons/base:12.2.7
  armv7: ghcr.io/hassio-addons/base:12.2.7
  i386: ghcr.io/hassio-addons/base:12.2.7
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
