---
build_from:
  aarch64: ghcr.io/hassio-addons/base-nodejs:0.2.4
  amd64: ghcr.io/hassio-addons/base-nodejs:0.2.4
  armv7: ghcr.io/hassio-addons/base-nodejs:0.2.4
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
