---
build_from:
  aarch64: ghcr.io/hassio-addons/base:14.0.6
  amd64: ghcr.io/hassio-addons/base:14.0.6
  armhf: ghcr.io/hassio-addons/base:14.0.6
  armv7: ghcr.io/hassio-addons/base:14.0.6
  i386: ghcr.io/hassio-addons/base:14.0.6
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev
