---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:10.2.2
  amd64: ghcr.io/hassio-addons/base/amd64:10.2.2
  armhf: ghcr.io/hassio-addons/base/armhf:10.2.2
  armv7: ghcr.io/hassio-addons/base/armv7:10.2.2
  i386: ghcr.io/hassio-addons/base/i386:10.2.2
