---
name: Node-RED
version: dev
slug: nodered
description: Flow-based programming for the Internet of Things
url: https://github.com/hassio-addons/addon-node-red
codenotary: codenotary@frenck.dev
ingress: true
ingress_port: 0
ingress_stream: true
panel_icon: mdi:sitemap
init: false
homeassistant: 2023.3.0
arch:
  - aarch64
  - amd64
  - armv7
ports:
  80/tcp: 1880
ports_description:
  80/tcp: Web interface
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
auth_api: true
uart: true
map:
  - addon_config:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl
backup_exclude:
  - "node_modules"
options:
  theme: default
  http_node:
    username: ""
    password: ""
  http_static:
    username: ""
    password: ""
  ssl: true
  certfile: fullchain.pem
  keyfile: privkey.pem
  system_packages: []
  npm_packages: []
  init_commands: []
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  credential_secret: password?
  theme: list(default|aurora|cobalt2|dark|dracula|espresso-libre|github-dark|github-dark-default|github-dark-dimmed|midnight-red|monoindustrial|monokai|monokai-dimmed|noctis|oceanic-next|oled|one-dark-pro|one-dark-pro-darker|solarized-dark|solarized-light|tokyo-night|tokyo-night-light|tokyo-night-storm|totallyinformation|zenburn)?
  http_node:
    username: str
    password: password
  http_static:
    username: str
    password: password
  ssl: bool
  certfile: str
  keyfile: str
  system_packages:
    - str
  npm_packages:
    - str
  init_commands:
    - str
  leave_front_door_open: bool?
  safe_mode: bool?
  max_old_space_size: int?
